sumaN1 = int(input("Digite un Numero: "))
sumaN2 = int(input("Digite un Numero: "))
# sumaN1 = str(sumaN1)
# sumaN2 = str(sumaN2)
respuesta = str(sumaN1 + sumaN2)
print("La operacion es: " + str(sumaN1) + " + " + str(sumaN2) + " = " + respuesta)
